ForumProject.PresentationLayer/Models/PagerViewModel.cs
using ForumProject.Entity;
using System;
using System.Collections.Generic;

namespace ForumProject.PresentationLayer.Models
{   
        public class PageInfo        
        {
            public int PageNumber { get; set; } 
            public int PageSize { get; set; } 
            public int TotalItems { get; set; } 
            public int TotalPages  
            {
                get { return (int)Math.Ceiling((decimal)TotalItems / PageSize); }
            }
        }

        public class ArticlePagingViewModel
        {
            public IEnumerable<ArticleViewModel> Articles { get; set; }
            public PageInfo PageInfo { get; set; }
        }
    
}

ForumProject.PresentationLayer/Controllers/ArticleController.cs
using System.Linq;
using System.Web.Mvc;
using ForumProject.BusinessLogicLayer;
using ForumProject.DataAccessLayer.Repository;
using ForumProject.Entity;
using ForumProject.PresentationLayer.Models;
using log4net;
using System.Data.Entity;


namespace ForumProject.PresentationLayer.Controllers
{
    public class ArticleController : Controller
    {
        private readonly FacilitiesFacade _facade = IoC.Container.GetInstance<FacilitiesFacade>();
        private readonly ILog m_logger = LogManager.GetLogger(typeof(ArticleController));
        [Authorize]
        public ActionResult Index(string sort="id_asc",int page=1)
        {            
                int pageSize = 5;
                int pageNumber = page; 
                var articles = _facade.GetCountArticles();
                var articlesPerPages = _facade.GetListByLimit(pageNumber,pageSize,sort).Select(ArticleMapper.ToViewModel).ToList();              
                PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = articles};
                ArticlePagingViewModel model = new ArticlePagingViewModel { PageInfo = pageInfo, Articles = articlesPerPages };
                           
                for (int i = 0; i < articlesPerPages.Count; i++)
                {
                    articlesPerPages[i].CountCommentByArticle = _facade.GetCountCommentByArticle(articlesPerPages[i].Id);
                }
                m_logger.Info("list of Articles");
                return View(model);               
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(ArticleViewModel model)
        {
            ModelState.Clear();
            m_logger.Info("Page to create articles");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken()]
        public ActionResult CreatePost(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Request.IsAuthenticated)
                {
                    model.NickName = User.Identity.Name;
                }
                else
                {
                    var listAuthors = _facade.GetAuthors();
                    string _CurrentUser = _facade.GetCurrentUser(listAuthors);
                    model.NickName = _CurrentUser;
                }
                m_logger.Info("Added new article");
                _facade.SaveArticle(model.ToModel()); 
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error creating article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(ArticleViewModel model)
        {
            var ModelById = _facade.GetArticleById(model.Id);
            model.ContentArticle = ModelById.ContentArticle;
            model.Title = ModelById.Title;
            m_logger.Info("Page to delete articles");
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int ID)
        {           
            if (ModelState.IsValid)
            {
                _facade.DeleteArticle(ID);
                m_logger.Info("Article deleted successfully");
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error deleting article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(ArticleViewModel model)
        {
            var ModelById = _facade.GetArticleById(model.Id);
            model.ContentArticle = ModelById.ContentArticle;
            model.Title = ModelById.Title;
            ModelState.Clear();
            m_logger.Info("Page to edit articles");
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.UpdateArticle(model.ToModel());
                m_logger.Info("Article edit successfully");
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error editing article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Show(ArticleViewModel model,int page=1)
         {
             
            var modelById = _facade.GetArticleById(model.Id);          
            model.ContentArticle = modelById.ContentArticle;
            model.Title = modelById.Title;
            var comments = _facade.GetBaseCommentByArticle(model.Id).Select(CommentMapper.ToViewModel).ToList();
            comments = comments.OrderByDescending(x => x.Id).ToList();
            int pageSize = 5;
            int pageNumber = page;
            var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };
            model.PageInfo = pageInfo;
            model.BaseComments = commentsPerPages;
            
            foreach (var item in model.BaseComments)
            {
                var user = _facade.GetUserById(item.User.Id);
                item.User.Id = item.IdUser;
                item.FirstNameUser=user.FirstName;
                 item.LastNameUser=user.LastName;
            }
            
            
            return View(model);
        }             

        [Authorize]     
        [HttpPost]
        public PartialViewResult Show(CommentViewModel model,ArticleViewModel article, int page=1)
        {
         var current_user= _facade.FindByIdentityName(User.Identity.Name);
        
         model.User.Id = current_user.Id;
         
           
                    _facade.SaveComment(model.ToModel());
                    var comments = _facade.GetBaseCommentByArticle(article.Id).Select(CommentMapper.ToViewModel).ToList();
                    comments = comments.OrderByDescending(x => x.Id).ToList();
                    int pageSize = 5;
                    int pageNumber = page;
                    var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                    PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };
                    article.PageInfo = pageInfo;
                    article.BaseComments = commentsPerPages;

                    foreach (var item in article.BaseComments)
                    {
                        var user = _facade.GetUserById(item.User.Id);
                        item.User.Id = item.IdUser;
                        item.FirstNameUser = user.FirstName;
                        item.LastNameUser = user.LastName;
                    }
                    return PartialView("~/Views/Comment/PartialListComment.cshtml", article);
                                 
        }        
      
    }
}

ForumProject.PresentationLayer/Controllers/CultureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForumProject.PresentationLayer.Controllers
{
    public class CultureController : Controller
    {
        public ActionResult ChangeCulture(Culture lang, string returnUrl)
        {
            if (returnUrl.Contains("/en/") ||returnUrl.Contains("/ru/"))
            {
                returnUrl = returnUrl.Substring(3);
            }
            
            return Redirect("/" + lang.ToString() + returnUrl);
        }      
    }
}

ForumProject.PresentationLayer/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using ForumProject.BusinessLogicLayer;
using ForumProject.DataAccessLayer.Repository;
using ForumProject.Entity;
using ForumProject.PresentationLayer.Models;
using PagedList.Mvc;
using PagedList;
using System.ComponentModel.DataAnnotations;
using WebMatrix.WebData;
using System;
using System.Web;
using System.IO;
using log4net;
using System.Globalization;

namespace ForumProject.PresentationLayer.Controllers
{
    public class UserController : Controller
    {
        private readonly FacilitiesFacade _facade = IoC.Container.GetInstance<FacilitiesFacade>();
        private readonly ILog m_logger = LogManager.GetLogger(typeof(UserController));
        [Authorize]
        public ActionResult Index(int? page, string sort)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).ToList();

            ViewBag.CurrentSort = sort;
            ViewBag.SortFirstName = String.IsNullOrEmpty(sort) ? "FirstName" : "";
            ViewBag.SortLastName = sort == "LastName" ? "LastNameDesc" : "LastName";
            ViewBag.SortBirthday = sort == "Birthday" ? "BirthdayDesc" : "Birthday";

            switch (sort)
            {
                case "FirstName":

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderByDescending(b => b.FirstName).ToList();
                    break;

                case "LastName":

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderBy(b => b.LastName).ToList();
                    break;

                case "LastNameDesc":

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderByDescending(b => b.LastName).ToList();
                    break;

                case "Birthday":

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderBy(b => b.Birthday).ToList();
                    break;

                case "BirthdayDesc":

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderByDescending(b => b.Birthday).ToList();
                    break;

                default:

                    viewModel = _facade.GetUsers().Select(UserMapper.ToViewModel).OrderBy(b => b.FirstName).ToList();
                    break;
            }
            foreach (UserViewModel user in viewModel)
            {
                user.Role = _facade.GetRoleForUser(user.Id);                
            }         
            return View(viewModel.ToPagedList(pageNumber, pageSize));
        }
        
        public ActionResult GetFile(int user_id)
        {
            string dir = Server.MapPath(String.Format("~/App_Data/Uploads/{0}/", user_id));
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
         
                string[] fullfilesPath = Directory.GetFiles(dir);
                string file_path;
  
                if (fullfilesPath.Length == 0)
                {
                    file_path = dir;
                    return null;
                }
                else
                {
                    file_path = Path.Combine(dir, fullfilesPath[0]);
                    return File(file_path, GetContentType(file_path));
                }            
           
        }
        
        private string GetContentType(string filename)
        {
            FileInfo file = new FileInfo(filename); 
            switch (file.Extension.ToUpper())
            {
                case ".PNG": return "image/png";
                case ".JPG": return "image/jpg";
                case ".JPEG": return "image/jpeg";
                case ".GIF": return "image/gif";
                case ".BMP": return "image/bmp";
                case ".TIFF": return "image/tiff";
               
                default:
                    throw new NotSupportedException("The Specified File Type Is Not Supported");
            }
        }
       
        [Authorize]
        [HttpGet]
        public ActionResult Delete(UserViewModel model)
        {
            model.Role = _facade.GetRoleForUser(model.Id);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int ID)
        { 
            if (ModelState.IsValid)
            {
                _facade.DeleteUser(ID);
                return this.RedirectToAction("Index");
            }
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(UserViewModel model)
        {
            model.Role = _facade.GetRoleForUser(model.Id);
            return View(model);
        }
               
        [HttpPut]
        public void UpdateUser(UserViewModel model)
        {       
            _facade.UpdateUser(model.ToModel());
            if (String.IsNullOrEmpty(model.Role))
            { model.Role = "2"; }
            _facade.UpdateRole(model.Id, model.Role);
        }

        [Authorize]
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(UserViewModel model, string id, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)            
            {
                try
                {
                    if (file != null && file.ContentLength > 0 && (file.ContentType.Contains("/jpg") || file.ContentType.Contains("/jpeg") || file.ContentType.Contains("/png") || file.ContentType.Contains("/bmp")))
                    {

                        string fileName = Path.GetFileName(file.FileName);
                        string dir = Server.MapPath(String.Format("~/App_Data/Uploads/{0}/", model.Id));
                      

                        DirectoryInfo dirInfo = new DirectoryInfo(dir);
                        dirInfo.Delete(true);

                        if (!Directory.Exists(dir))
                        {
                            Directory.CreateDirectory(dir);
                        }

                        string path = Path.Combine(dir, fileName);

                        file.SaveAs(path);

                        _facade.UpdateUser(model.ToModel());
                        if (String.IsNullOrEmpty(model.Role))
                        { model.Role = "2"; }
                        _facade.UpdateRole(model.Id, model.Role);
                        return this.RedirectToAction("Index");

                    }
                    else
                    {
                        ViewBag.Msg = "Invalid File";
                        m_logger.Error("Upload Invalid File");
                        return this.View();
                    }
                }
                catch (FileNotFoundException fileNotFoundException)
                {
                   m_logger.Error(fileNotFoundException);
                }
                catch (DirectoryNotFoundException directoryNotFoundException)
                {
                    m_logger.Error(directoryNotFoundException);
                }
                catch (IOException ioException)
                {
                    m_logger.Error(ioException);
                }
                catch (HttpException e)
                {
                    throw new ApplicationException("Cannot save uploaded file", e);
                }
                               
             
            }
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(UserViewModel model)
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [ActionName("Create")]
        public ActionResult CreatePost(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.SaveUser(model.ToModel());
                return this.RedirectToAction("Index");
            }

            return this.View();
        }

        [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
        public class DateValidationAttribute : ValidationAttribute
        {
            public DateValidationAttribute()
            {
            }

            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                if (value != null)
                {
                    DateTime date;

                    if (value is string)
                    {
                        if (!DateTime.TryParse((string)value, out date))
                        {
                            return new ValidationResult(validationContext.DisplayName + " must be a valid date.");
                        }
                    }
                    else
                        date = (DateTime)value;

                    if (date < new DateTime(1900, 1, 1) || date > new DateTime(3000, 12, 31))
                    {
                        return new ValidationResult(validationContext.DisplayName + " must be a valid date.");
                    }
                }
                return null;
            }
        }
    }
}

ForumProject.PresentationLayer/Views/Shared/FileNotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo
@{
    Layout = "_Layout.cshtml";
    ViewBag.Title = "Error";
}
<div class="list-header clearfix">
    <span>Error</span>
</div>
<div class="list-sfs-holder">
    <div class="alert alert-error">
        An unexpected error has occurred. Please contact the system administrator.
    </div>
    @if (Model != null && HttpContext.Current.IsDebuggingEnabled)
    {
        <div>
            <p>
                <b>Exception:</b> @Model.Exception.Message<br />
                <b>Controller:</b> @Model.ControllerName<br />
                <b>Action:</b> @Model.ActionName
            </p>
            <div style="overflow:scroll">
                <pre>
@Model.Exception.StackTrace
                </pre>
            </div>
        </div>
    }
</div>

ForumProject.PresentationLayer/Views/Shared/LoginPartial.cshtml
@if (Request.IsAuthenticated)
{
    <h>@Resources.Resource.Welcome,@User.Identity.Name!</h>
    @Html.ActionLink(@Resources.Resource.LogOff, "LogOff", "Account") 
}

else
{
    @Html.ActionLink(@Resources.Resource.LogOn, "Login", "Account") 
}

ForumProject.PresentationLayer/Views/Shared/Pager.cshtml
@using ForumProject.PresentationLayer.Models
@model IPager

@System.Web.Optimization.Scripts.Render( 
                    "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie")
<div class="pager">
    @if (Model.CurrentPage > 1)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(Model.CurrentPage - 1)">Предыдущая</a>
    }
    @if (Model.StartDisplayedPage > 1)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(1)">1</a>
        if (Model.StartDisplayedPage > 2)
        {
        <a class="pager-link" href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a>
        }
    }
    @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
    {
        if (i == Model.CurrentPage)
        {
            <span class="pager-text">@i</span>
        }
        else
        {
            <a class="pager-link" href="@Model.GetLinkForPage(i)">@i</a>
        }
    }
    @if (Model.EndDisplayedPage < Model.PageCount)
    {
        if (Model.EndDisplayedPage < Model.PageCount - 1)
        {
            <a class="pager-link" href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a>
        }
        <a class="pager-link" href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a>
    }
    @if (Model.CurrentPage < Model.PageCount)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(Model.CurrentPage + 1)">Следующая</a>
    }
</div>

ForumProject.PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />

    @System.Web.Optimization.Styles.Render("~/Content/css",
                "~/Content/themes/base/css")

    @System.Web.Optimization.Scripts.Render(
                "~/bundles/modernizr")
</head>

<body>
    <div id="gwrapper">
        <div class="gheader">
            <div class="gheader1">
                <div class="label_for_logo">@Resources.Resource.Forum</div>
                <div style="float: right; margin-right: 50px">

                    <div class="img_for_login">
                        <img src="/Content/themes/base/images/login_user.png" width="50" height="50">
                    </div>

                    <div class="label_for_login">@Html.Partial("LoginPartial")</div>
                    <div id="lang"></div>

                </div>
            </div>

            <div class="gheader2">

                <ul id="nav" style="float: left">

                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(@Resources.Resource.Articles, "Index", "Article")</li>                                           
                        <li>@Html.ActionLink(@Resources.Resource.Users, "Index", "User")</li>                   
                                             
                    }

                    <li style="float: right">@Html.ActionLink("Русский", "ChangeCulture", "Culture", new { lang = (int)ForumProject.PresentationLayer.Culture.ru, returnUrl = this.Request.RawUrl }, null)</li>
                    <li style="float: right">@Html.ActionLink("English", "ChangeCulture", "Culture", new { lang = (int)ForumProject.PresentationLayer.Culture.en, returnUrl = this.Request.RawUrl }, null)</li>
                
                </ul>
            </div>
        </div>

        <div class="gcontent">
            <div class="gcontent-in">
                <div class="gcontent-in2">

                    <div id="Index Content Here">
                        @RenderBody()
                    </div>

                </div>
            </div>
        </div>
        
        <div class="gfooter">
            <div class="gfooter-in">

                <div class="gfooter1">
                    ForumProject,2015
                </div>

                <div class="gfooter2">
                    Copyright
                </div>

            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>