ForumProject.PresentationLayer/Models/ArticleViewModel.cs
using System;
using ForumProject.Entity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace ForumProject.PresentationLayer.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is required!")]
        [Display(Name = "Title")]      
        public String Title { get; set; }

        [Required(ErrorMessage = "Content is required!")]    
        [Display(Name = "Content")]  
        public String ContentArticle { get; set; }        
        public String NickName { get; set; }

        public List<CommentViewModel> BaseComments { get; set; }
        public int CountCommentByArticle { get; set; }

        public PageInfo PageInfo { get; set; }
        public IEnumerable<CommentViewModel> Comments { get; set; }
        
        public string PageTitle { get; set; }
        public IEnumerable<Article> ArticleList { get; set; }
        public int ArticleCount { get; set; }

        
    }
}

ForumProject.PresentationLayer/Controllers/ArticleController.cs
using System.Linq;
using System.Web.Mvc;
using ForumProject.BusinessLogicLayer;
using ForumProject.DataAccessLayer.Repository;
using ForumProject.Entity;
using ForumProject.PresentationLayer.Models;
using log4net;
using System.Data.Entity;


namespace ForumProject.PresentationLayer.Controllers
{
    public class ArticleController : Controller
    {
        private readonly FacilitiesFacade _facade = IoC.Container.GetInstance<FacilitiesFacade>();
        private readonly ILog m_logger = LogManager.GetLogger(typeof(ArticleController));
        [Authorize]
        public ActionResult Index(string sort="id_asc",int page=1)
        {            
                int pageSize = 5;
                int pageNumber = page; 
                var articles = _facade.GetCountArticles();
                var articlesPerPages = _facade.GetListByLimit(pageNumber,pageSize,sort).Select(ArticleMapper.ToViewModel).ToList();              
                PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = articles};
                ArticlePagingViewModel model = new ArticlePagingViewModel { PageInfo = pageInfo, Articles = articlesPerPages };
                           
                for (int i = 0; i < articlesPerPages.Count; i++)
                {
                    articlesPerPages[i].CountCommentByArticle = _facade.GetCountCommentByArticle(articlesPerPages[i].Id);
                }
                m_logger.Info("list of Articles");
                return View(model);               
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(ArticleViewModel model)
        {
            ModelState.Clear();
            m_logger.Info("Page to create articles");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken()]
        public ActionResult CreatePost(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Request.IsAuthenticated)
                {
                    model.NickName = User.Identity.Name;
                }
                else
                {
                    var listAuthors = _facade.GetAuthors();
                    string _CurrentUser = _facade.GetCurrentUser(listAuthors);
                    model.NickName = _CurrentUser;
                }
                m_logger.Info("Added new article");
                _facade.SaveArticle(model.ToModel()); 
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error creating article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(ArticleViewModel model)
        {
            var ModelById = _facade.GetArticleById(model.Id);
            model.ContentArticle = ModelById.ContentArticle;
            model.Title = ModelById.Title;
            m_logger.Info("Page to delete articles");
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int ID)
        {           
            if (ModelState.IsValid)
            {
                _facade.DeleteArticle(ID);
                m_logger.Info("Article deleted successfully");
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error deleting article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(ArticleViewModel model)
        {
            var ModelById = _facade.GetArticleById(model.Id);
            model.ContentArticle = ModelById.ContentArticle;
            model.Title = ModelById.Title;
            ModelState.Clear();
            m_logger.Info("Page to edit articles");
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.UpdateArticle(model.ToModel());
                m_logger.Info("Article edit successfully");
                return this.RedirectToAction("Index");
            }
            m_logger.Error("Error editing article. Enter valid values");
            return this.View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Show(ArticleViewModel model,int page=1)
         {
             
            var modelById = _facade.GetArticleById(model.Id);          
            model.ContentArticle = modelById.ContentArticle;
            model.Title = modelById.Title;
            var comments = _facade.GetBaseCommentByArticle(model.Id).Select(CommentMapper.ToViewModel).ToList();
            comments = comments.OrderByDescending(x => x.Id).ToList();
            int pageSize = 5;
            int pageNumber = page;
            var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };
            model.PageInfo = pageInfo;
            model.BaseComments = commentsPerPages;
            
            foreach (var item in model.BaseComments)
            {
                var user = _facade.GetUserById(item.User.Id);
                item.User.Id = item.IdUser;
                item.FirstNameUser=user.FirstName;
                 item.LastNameUser=user.LastName;
            }
            
            
            return View(model);
        }             

        [Authorize]     
        [HttpPost]
        public PartialViewResult Show(CommentViewModel model,ArticleViewModel article, int page=1)
        {
         var current_user= _facade.FindByIdentityName(User.Identity.Name);
        
         model.User.Id = current_user.Id;
         
           
                    _facade.SaveComment(model.ToModel());
                    var comments = _facade.GetBaseCommentByArticle(article.Id).Select(CommentMapper.ToViewModel).ToList();
                    comments = comments.OrderByDescending(x => x.Id).ToList();
                    int pageSize = 5;
                    int pageNumber = page;
                    var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                    PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };
                    article.PageInfo = pageInfo;
                    article.BaseComments = commentsPerPages;

                    foreach (var item in article.BaseComments)
                    {
                        var user = _facade.GetUserById(item.User.Id);
                        item.User.Id = item.IdUser;
                        item.FirstNameUser = user.FirstName;
                        item.LastNameUser = user.LastName;
                    }
                    return PartialView("~/Views/Comment/PartialListComment.cshtml", article);
                                 
        }        
      
    }
}

ForumProject.PresentationLayer/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForumProject.BusinessLogicLayer;
using ForumProject.DataAccessLayer.Repository;
using ForumProject.Entity;
using ForumProject.PresentationLayer.Models;
using PagedList.Mvc;
using PagedList;
using log4net;

namespace ForumProject.PresentationLayer.Controllers
{
    public class CommentController : Controller
    {
        private readonly FacilitiesFacade _facade = IoC.Container.GetInstance<FacilitiesFacade>();
        private readonly ILog m_logger = LogManager.GetLogger(typeof(CommentController));
        [Authorize]
        [HttpGet]
        public ActionResult PartialListComment(ArticleViewModel model, int idArticle, int page = 1)
        {
            model.Id = idArticle;
            var modelById = _facade.GetArticleById(model.Id);            
            model.ContentArticle = modelById.ContentArticle;
            model.Title = modelById.Title;
            var comments = _facade.GetBaseCommentByArticle(model.Id).Select(CommentMapper.ToViewModel).ToList();

            comments = comments.OrderByDescending(x => x.Id).ToList();

            int pageSize = 5;
            int pageNumber = page;

            var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };

            model.PageInfo = pageInfo;
            model.BaseComments = commentsPerPages;
            foreach (var item in model.BaseComments)
            {
                var user = _facade.GetUserById(item.User.Id);
                item.User.Id = item.IdUser;
                item.FirstNameUser = user.FirstName;
                item.LastNameUser = user.LastName;
            }
            return PartialView(model);
        } 

        [Authorize]
        [HttpPost]
        public PartialViewResult PartialListComment(CommentViewModel model, int idComment, int idArticle,int page=1)
        {
            _facade.DeleteComment(idComment);
            ArticleViewModel articleModel = new ArticleViewModel();
            var modelById = _facade.GetArticleById(idArticle);
            var comments = _facade.GetBaseCommentByArticle(idArticle).Select(CommentMapper.ToViewModel).ToList();

            comments = comments.OrderByDescending(x => x.Id).ToList();

            int pageSize = 5;
            int pageNumber = page;

            var commentsPerPages = comments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comments.Count };

            articleModel.PageInfo = pageInfo;
            articleModel.BaseComments = commentsPerPages;
            articleModel.Id = idArticle;
            foreach (var item in articleModel.BaseComments)
            {
                var user = _facade.GetUserById(item.User.Id);
                item.User.Id = item.IdUser;
                item.FirstNameUser = user.FirstName;
                item.LastNameUser = user.LastName;
            }
            return PartialView("~/Views/Comment/PartialListComment.cshtml", articleModel);

        }
    }
}

ForumProject.PresentationLayer/Views/Article/Create.cshtml
@model ForumProject.PresentationLayer.Models.ArticleViewModel
@{
    ViewBag.Title = "Create article";   
}
@System.Web.Optimization.Scripts.Render(
                    "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie", "~/bundles/myScripts")

@using (Html.BeginForm("Create", "Article", FormMethod.Post))
{
    <h2>
        <img src="/Content/themes/base/images/create_article.png" height="30" width="30">
        @Resources.Resource.CreateNewArticle
    </h2>
    
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
   
     <fieldset>

        <legend></legend>

        <div class="editor-label">
            @Html.Label(@Resources.Resource.TitleArticle)
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => Model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.Label(@Resources.Resource.ContentArticle)
        </div>
         
        <div class="editor-field">
            @Html.TextAreaFor(model => Model.ContentArticle, new { @class = "text-box multi-line " })
            @Html.ValidationMessageFor(model => model.ContentArticle)
        </div>

        <p style="text-align: center">
            <input type="submit" class="button" value="@Resources.Resource.SaveNewTopic" />
        </p>

    </fieldset>


    <div>
        <a href class="link_back">@Resources.Resource.BackToList</a>
    </div>
}

ForumProject.PresentationLayer/Views/Article/Delete.cshtml
@model ForumProject.PresentationLayer.Models.ArticleViewModel
@{
    ViewBag.Title = "Remove article";
    
}
@System.Web.Optimization.Scripts.Render(
                    "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie", "~/bundles/myScripts")

@using (Html.BeginForm("Delete", "Article", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>
        <img src="/Content/themes/base/images/delete_article.png" height="30" width="30">
        @Resources.Resource.RemoveArticle " @Model.Title "             
    </h2>
    
    <fieldset>
        <div id="content_topic">
            @Model.ContentArticle
        </div>
    </fieldset>   
    
    <p style="text-align: center">
        <input type="submit" value="@Resources.Resource.RemoveArticle" class="button" />
    </p>
   
}

<div>
    <a href class="link_back">@Resources.Resource.BackToList</a>
</div>

ForumProject.PresentationLayer/Views/Article/Edit.cshtml
@model ForumProject.PresentationLayer.Models.ArticleViewModel
@{
    ViewBag.Title = "Edit article";

}

@System.Web.Optimization.Scripts.Render("~/bundles/microsoftajax",
                    "~/bundles/datepicker",
                     "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie", "~/bundles/myScripts")
<h2>
    <img src="/Content/themes/base/images/edited_article.png" height="30" width="30">
    @Resources.Resource.EditTopic
</h2>

@using (Html.BeginForm("Edit", "Article", FormMethod.Post))
{
    
    <fieldset>

        @Html.Label(@Resources.Resource.TitleArticle)

        <div class="editor-field">
            @Html.EditorFor(model => Model.Title)
            @Html.ValidationMessageFor(model => Model.Title)
        </div>

        <br />
        @Html.Label(@Resources.Resource.ContentArticle)

        <div class="editor-field">
            @Html.TextAreaFor(model => Model.ContentArticle, new { @class = "text-box multi-line " })
            @Html.ValidationMessageFor(model => Model.ContentArticle)
        </div>

        <p style="text-align: center">
            <input type="submit" class="button" value="@Resources.Resource.SaveTopic" />
        </p>

    </fieldset>
}

<div>
    <a href class="link_back">@Resources.Resource.BackToList</a>
</div>

ForumProject.PresentationLayer/Views/Article/Index.cshtml
@using ForumProject.PresentationLayer.Models
@model ForumProject.PresentationLayer.Models.ArticlePagingViewModel
@using PagedList.Mvc;
@using ForumProject.PresentationLayer.Helpers;

@{
    ViewBag.Title = "Index";  
}

@System.Web.Optimization.Scripts.Render(
                    "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie",
                    "~/bundles/ListGridView",
                    "~/bundles/myScripts")



<div id="container">

    <div class="buttons">
        @Html.ActionLink(@Resources.Resource.NewTopic, "Create")

        <button class="grid">
            <img src="../../Content/themes/base/images/grid.png" height="30" width="30"></button>
        <button class="list">
            <img src="../../Content/themes/base/images/list.png"></button>

        <div class="wrapper">
            <div class="droplink">
                <h3><a href="#">@Resources.Resource.Sorting</a></h3>
                <ul>
                    <li>@Html.ActionLink(@Resources.Resource.SortingA, "Index", new { sort = "name_asc" })</li>
                    <li>@Html.ActionLink(@Resources.Resource.SortingZ, "Index", new { sort = "name_desc" })</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <table class="list">

        @foreach (ArticleViewModel item in Model.Articles)
        {
               
            <tr>
                <td id="str1">@Html.ActionLink(item.Title, "Show", new { item.Id }, new { @class = "link" })


                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.Identity.Name == item.NickName)
                    {
                    

                        <a href="@Url.Action("Delete", new { item.Id })">
                            <img src="@Url.Content("~/Content/themes/base/images/remove.png")" height="20" width="20", alt="Delete" />
                        </a>

                        <a href="@Url.Action("Edit", new { item.Id })">
                            <img src="@Url.Content("~/Content/themes/base/images/Edit.png")" height="20" width="20", alt="Edit" />
                        </a>

                    }
                </td>
                <td id="str2">@item.CountCommentByArticle comments</td>
                <td id="str3">@Resources.Resource.Author: @item.NickName</td>

            </tr>       
        }

    </table>
</div>
<div id="page">
    <div class="pagination">
        <p>@Resources.Resource.Page @(Model.PageInfo.TotalItems < Model.PageInfo.PageNumber ? 0 : Model.PageInfo.PageNumber) @Resources.Resource.PageOf @Model.PageInfo.TotalPages</p>
        @Html.PageLinks(Model.PageInfo.PageNumber, Model.PageInfo.TotalPages, page => Url.Action("Index", new { page = page }))
    </div>
</div>
<script>
    $(function () {
        var view = $.cookie('list_grid');
        if (view == 'grid') {
            $('#container table').addClass('grid');
        }
        else {
            $('#container table').addClass('list');
        }

    });

    $('button').on('click', function (e) {
        if ($(this).hasClass('grid')) {
            $('#container table').removeClass('list').addClass('grid');

            $.cookie('list_grid', 'grid');
        }
        else if ($(this).hasClass('list')) {
            $('#container table').removeClass('grid').addClass('list');
            $.cookie('list_grid', null);
        }
    });



</script>

ForumProject.PresentationLayer/Views/Article/Show.cshtml
@model ForumProject.PresentationLayer.Models.ArticleViewModel

@{
    ViewBag.Title = "Show";
}

@System.Web.Optimization.Scripts.Render( 
                    "~/bundles/jquery",
                    "~/bundles/jqueryui",
                    "~/bundles/jqueryval",
                    "~/bundles/cookie", "~/bundles/myScripts")

 @using (Ajax.BeginForm("Show", "Article", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "update", OnComplete = "ClearForm()" }))
 {        
     
        <div class="name_topic">@Resources.Resource.Topic: @Model.Title</div>        

        <div id="content_topic">@Model.ContentArticle</div>       

        <div style="width: 100%; float: left;">

             <div style="float: left; width: 50%;">
                <div style="margin: 10px; padding: 10px;" id="items_list">                    
                    <div id ="update">
                    @{Html.RenderPartial("~/Views/Comment/PartialListComment.cshtml");}       
                    </div>                                      
                </div>
            </div>


            <div style="float: left; width: 50%;">
                <div style="margin: 10px; padding: 10px;">
                 <div id="input">
                    @Html.Partial("~/Views/Comment/Create.cshtml", new ViewDataDictionary())
                 </div>
                 <p>
                    <input type="submit" value="@Resources.Resource.PostComment" id="post" />
                 </p>
                </div>
            </div>
        </div>

        <div style="clear: both;"></div>
 }

    <div>
        <a href class="link_back">@Resources.Resource.BackToList</a>
    </div>


<script>

    function DeleteComment(idArticle, idComment) {

        var idComment = idComment;
        var idArticle = idArticle;

        $.ajax({
            type: "POST",
            url: '@Url.Action("PartialListComment", "Comment")',
            data: "idArticle=" + idArticle + "&idComment=" + idComment,
            success: function (articleModel) {
                
                $('#update').html(articleModel);
            }
        });

    }

    function Paging(idArticle, page) {

               var page = page;
               var idArticle = idArticle;

               $.ajax({
                   url: '@Url.Action("PartialListComment","Comment")',
                   data: {
                      "page": page,
                      "idArticle": idArticle,
                   },
                success: function (data) {
                    $("#update").html(data);
                }
            });
        }

    function ClearForm() {
        $('form').find("input[name='TitleBaseComment']").val("");
       $('form').find("$('textarea')[name='ContentBaseComment']").val("");
    }
</script>